In [2]:
# Attempt at http://www.utstat.toronto.edu/~guerzhoy/303/proj/P2/soln/p2credit.html
# and converting the example into python
# Imports
import numpy as np
import pandas as pd
import scorecardpy as sc

In [16]:
df = pd.read_csv('germancredit.csv')

In [17]:
df.head()

,Default,checkingstatus1,duration,history,purpose,amount,savings,employ,installment,status,...,residence,property,age,otherplans,housing,cards,job,liable,tele,foreign
0,0,A11,6,A34,A43,1169,A65,A75,4,A93,...,4,A121,67,A143,A152,2,A173,1,A192,A201
1,1,A12,48,A32,A43,5951,A61,A73,2,A92,...,2,A121,22,A143,A152,1,A173,1,A191,A201
2,0,A14,12,A34,A46,2096,A61,A74,2,A93,...,3,A121,49,A143,A152,1,A172,2,A191,A201
3,0,A11,42,A32,A42,7882,A61,A74,2,A93,...,4,A122,45,A143,A153,1,A173,2,A191,A201
4,1,A11,24,A33,A40,4870,A61,A73,3,A93,...,4,A124,53,A143,A153,2,A173,2,A191,A201

In [21]:
df.info()
# 8 Numerical Columns
# 13 Categorical Columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
Default            1000 non-null int64
checkingstatus1    1000 non-null object
duration           1000 non-null int64
history            1000 non-null object
purpose            1000 non-null object
amount             1000 non-null int64
savings            1000 non-null object
employ             1000 non-null object
installment        1000 non-null int64
status             1000 non-null object
others             1000 non-null object
residence          1000 non-null int64
property           1000 non-null object
age                1000 non-null int64
otherplans         1000 non-null object
housing            1000 non-null object
cards              1000 non-null int64
job                1000 non-null object
liable             1000 non-null int64
tele               1000 non-null object
foreign            1000 non-null object
dtypes: int64(8), object(13)
memory usage: 164.2+ KB

In [20]:
df.describe()

,Default,duration,amount,installment,residence,age,cards,liable
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.300000,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,0.458487,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,0.000000,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,0.000000,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,0.000000,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,1.000000,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,1.000000,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

In [18]:
bins = sc.woebin(df, 'Default')

[INFO] creating woe binning ...
Binning on 1000 rows and 21 columns in 00:00:10

In [19]:
for k, bin_ in bins.items():
    print(bin_)

   variable   bin  count  count_distr  good  bad   badprob       woe  \
0  property  A121    282        0.282   222   60  0.212766 -0.461035
1  property  A122    232        0.232   161   71  0.306034  0.028573
2  property  A123    332        0.332   230  102  0.307229  0.034191
3  property  A124    154        0.154    87   67  0.435065  0.586082

     bin_iv  total_iv breaks  is_special_values
0  0.054007  0.112638   A121              False
1  0.000190  0.112638   A122              False
2  0.000391  0.112638   A123              False
3  0.058050  0.112638   A124              False
      variable         bin  count  count_distr  good  bad   badprob       woe  \
0  installment  [-inf,3.0)    367        0.367   271   96  0.261580 -0.190473
1  installment   [3.0,4.0)    157        0.157   112   45  0.286624 -0.064539
2  installment   [4.0,inf)    476        0.476   317  159  0.334034  0.157300

     bin_iv  total_iv breaks  is_special_values
0  0.012789  0.025569    3.0              False
1  0.000645  0.025569    4.0              False
2  0.012135  0.025569    inf              False
  variable          bin  count  count_distr  good  bad   badprob       woe  \
0      age  [-inf,26.0)    190        0.190   110   80  0.421053  0.528844
1      age  [26.0,28.0)    101        0.101    74   27  0.267327 -0.160930
2      age  [28.0,35.0)    257        0.257   172   85  0.330739  0.142455
3      age  [35.0,37.0)     79        0.079    67   12  0.151899 -0.872488
4      age   [37.0,inf)    373        0.373   277   96  0.257373 -0.212371

     bin_iv  total_iv breaks  is_special_values
0  0.057921  0.130499   26.0              False
1  0.002529  0.130499   28.0              False
2  0.005359  0.130499   35.0              False
3  0.048610  0.130499   37.0              False
4  0.016080  0.130499    inf              False
  variable        bin  count  count_distr  good  bad   badprob       woe  \
0   status  A93%,%A94    640         0.64   469  171  0.267188 -0.161641
1   status        A92    310         0.31   201  109  0.351613  0.235341
2   status        A91     50         0.05    30   20  0.400000  0.441833

     bin_iv  total_iv     breaks  is_special_values
0  0.016164  0.044615  A93%,%A94              False
1  0.017931  0.044615        A92              False
2  0.010520  0.044615        A91              False
  variable          bin  count  count_distr  good  bad   badprob       woe  \
0      job         A172    200         0.20   144   56  0.280000 -0.097164
1      job         A173    630         0.63   444  186  0.295238 -0.022780
2      job  A171%,%A174    170         0.17   112   58  0.341176  0.189242

     bin_iv  total_iv       breaks  is_special_values
0  0.001851  0.008484         A172              False
1  0.000325  0.008484         A173              False
2  0.006308  0.008484  A171%,%A174              False
  variable              bin  count  count_distr  good  bad   badprob  \
0   amount    [-inf,1400.0)    267        0.267   185   82  0.307116
1   amount  [1400.0,1800.0)    105        0.105    87   18  0.171429
2   amount  [1800.0,4000.0)    382        0.382   287   95  0.248691
3   amount  [4000.0,9200.0)    196        0.196   120   76  0.387755
4   amount     [9200.0,inf)     50        0.050    21   29  0.580000

        woe    bin_iv  total_iv  breaks  is_special_values
0  0.033661  0.000305   0.18122  1400.0              False
1 -0.728239  0.046815   0.18122  1800.0              False
2 -0.258307  0.024109   0.18122  4000.0              False
3  0.390539  0.031987   0.18122  9200.0              False
4  1.170071  0.078005   0.18122     inf              False
  variable         bin  count  count_distr  good  bad   badprob       woe  \
0   liable  [-inf,2.0)    845        0.845   591  254  0.300592  0.002816
1   liable   [2.0,inf)    155        0.155   109   46  0.296774 -0.015409

     bin_iv  total_iv breaks  is_special_values
0  0.000007  0.000043    2.0              False
1  0.000037  0.000043    inf              False
  variable                                       bin  count  count_distr  \
0  purpose                                 A48%,%A41    112        0.112
1  purpose                                       A43    280        0.280
2  purpose  A42%,%A44%,%A49%,%A45%,%A40%,%A410%,%A46    608        0.608

   good  bad   badprob       woe    bin_iv  total_iv  \
0    94   18  0.160714 -0.805625  0.059846  0.152924
1   218   62  0.221429 -0.410063  0.042959  0.152924
2   388  220  0.361842  0.279920  0.050119  0.152924

                                     breaks  is_special_values
0                                 A48%,%A41              False
1                                       A43              False
2  A42%,%A44%,%A49%,%A45%,%A40%,%A410%,%A46              False
          variable        bin  count  count_distr  good  bad   badprob  \
0  checkingstatus1        A14    394        0.394   348   46  0.116751
1  checkingstatus1        A13     63        0.063    49   14  0.222222
2  checkingstatus1  A12%,%A11    543        0.543   303  240  0.441989

        woe    bin_iv  total_iv     breaks  is_special_values
0 -1.176263  0.404410  0.639372        A14              False
1 -0.405465  0.009461  0.639372        A13              False
2  0.614204  0.225501  0.639372  A12%,%A11              False
     variable          bin  count  count_distr  good  bad   badprob       woe  \
0  otherplans         A143    814        0.814   590  224  0.275184 -0.121179
1  otherplans  A142%,%A141    186        0.186   110   76  0.408602  0.477551

     bin_iv  total_iv       breaks  is_special_values
0  0.011656  0.057592         A143              False
1  0.045936  0.057592  A142%,%A141              False
  variable        bin  count  count_distr  good  bad   badprob       woe  \
0   employ        A74    174        0.174   135   39  0.224138 -0.394415
1   employ        A75    253        0.253   189   64  0.252964 -0.235566
2   employ        A73    339        0.339   235  104  0.306785  0.032103
3   employ  A71%,%A72    234        0.234   141   93  0.397436  0.431137

     bin_iv  total_iv     breaks  is_special_values
0  0.024792  0.085301        A74              False
1  0.013349  0.085301        A75              False
2  0.000352  0.085301        A73              False
3  0.046809  0.085301  A71%,%A72              False
    variable         bin  count  count_distr  good  bad   badprob       woe  \
0  residence  [-inf,2.0)    130        0.130    94   36  0.276923 -0.112478
1  residence   [2.0,3.0)    308        0.308   211   97  0.314935  0.070151
2  residence   [3.0,4.0)    149        0.149   106   43  0.288591 -0.054941
3  residence   [4.0,inf)    413        0.413   289  124  0.300242  0.001153

         bin_iv  total_iv breaks  is_special_values
0  1.606828e-03  0.003589    2.0              False
1  1.536634e-03  0.003589    3.0              False
2  4.447614e-04  0.003589    4.0              False
3  5.489228e-07  0.003589    inf              False
  variable         bin  count  count_distr  good  bad   badprob       woe  \
0    cards  [-inf,2.0)    633        0.633   433  200  0.315956  0.074877
1    cards   [2.0,inf)    367        0.367   267  100  0.272480 -0.134781

     bin_iv  total_iv breaks  is_special_values
0  0.003601  0.010084    2.0              False
1  0.006482  0.010084    inf              False
  variable   bin  count  count_distr  good  bad   badprob       woe    bin_iv  \
0     tele  A192    404        0.404   291  113  0.279703 -0.098638  0.003852
1     tele  A191    596        0.596   409  187  0.313758  0.064691  0.002526

   total_iv breaks  is_special_values
0  0.006378   A192              False
1  0.006378   A191              False
  variable          bin  count  count_distr  good  bad  badprob  woe  bin_iv  \
0  foreign  A202%,%A201   1000          1.0   700  300      0.3  0.0     0.0

   total_iv       breaks  is_special_values
0       0.0  A202%,%A201              False
  variable        bin  count  count_distr  good  bad   badprob       woe  \
0  history        A34    293        0.293   243   50  0.170648 -0.733741
1  history        A33     88        0.088    60   28  0.318182  0.085158
2  history        A32    530        0.530   361  169  0.318868  0.088319
3  history  A31%,%A30     89        0.089    36   53  0.595506  1.234071

     bin_iv  total_iv     breaks  is_special_values
0  0.132423   0.29183        A34              False
1  0.000649   0.29183        A33              False
2  0.004206   0.29183        A32              False
3  0.154553   0.29183  A31%,%A30              False
  variable          bin  count  count_distr  good  bad   badprob       woe  \
0   others         A103     52        0.052    42   10  0.192308 -0.587787
1   others  A101%,%A102    948        0.948   658  290  0.305907  0.027974

     bin_iv  total_iv       breaks  is_special_values
0  0.015674   0.01642         A103              False
1  0.000746   0.01642  A101%,%A102              False
   variable          bin  count  count_distr  good  bad   badprob       woe  \
0  duration   [-inf,8.0)     87        0.087    78    9  0.103448 -1.312186
1  duration   [8.0,16.0)    344        0.344   264   80  0.232558 -0.346625
2  duration  [16.0,34.0)    399        0.399   270  129  0.323308  0.108688
3  duration  [34.0,44.0)    100        0.100    58   42  0.420000  0.524524
4  duration   [44.0,inf)     70        0.070    30   40  0.571429  1.134980

     bin_iv  total_iv breaks  is_special_values
0  0.106849  0.282618    8.0              False
1  0.038294  0.282618   16.0              False
2  0.004813  0.282618   34.0              False
3  0.029973  0.282618   44.0              False
4  0.102689  0.282618    inf              False
  variable   bin  count  count_distr  good  bad   badprob       woe    bin_iv  \
0  housing  A152    713        0.713   527  186  0.260870 -0.194156  0.025795
1  housing  A151    179        0.179   109   70  0.391061  0.404445  0.031393
2  housing  A153    108        0.108    64   44  0.407407  0.472604  0.026106

   total_iv breaks  is_special_values
0  0.083293   A152              False
1  0.083293   A151              False
2  0.083293   A153              False
  variable              bin  count  count_distr  good  bad   badprob  \
0  savings  A64%,%A63%,%A65    294        0.294   245   49  0.166667
1  savings              A62    103        0.103    69   34  0.330097
2  savings              A61    603        0.603   386  217  0.359867

        woe    bin_iv  total_iv           breaks  is_special_values
0 -0.762140  0.142266  0.190974  A64%,%A63%,%A65              False
1  0.139552  0.002060  0.190974              A62              False
2  0.271358  0.046648  0.190974              A61              False

Default
checkingstatus1
duration
history
purpose
amount
savings
employ
installment
status
others
residence
property
age
otherplans
housing
cards
job
liable
tele
foreign